components in React
NosatskyiK/fe-react-2024 pull request #4
Opened 2024-05-10 12:57 UTC by NosatskyiK

Acceptance Criteria for 1

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  The ProductsList component correctly receives product data as props.
- [ ]  ProductCard component created and renders a single product.
- [ ]  Header and Footer elements are present.
- [ ]  ProductList displays right on mobile devices

Acceptance Criteria for 1*
 

- [ ] The Header component has clickable elements that toggle the display between the About and ProductsList components.
- [ ]  State management is handled in App.tsx, with state determining which component to show.
- [ ]  LocalStorage added to save items in card after page realod

2024-05-10 14:08 UTC, vadym-zinchenko-moc requested changes

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/cart/Cart.component.tsx
> +    const toggleCart = () => {
it's extra method, you can use method `setAdded`

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/cart/Cart.component.tsx
> +import React, { useState } from 'react';
why you import `React`?

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/App.tsx
> +import React, { useState } from 'react';
why you import `React`?

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/cart/Cart.component.tsx
> +    const [hasNotAdded, setAdded] = useState(false);
Bad naming. You must have the same name method and variable just to add `set` 
example - `[count, setCount]`

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/productList/ProductList.component.tsx
> +        <ProductCard data={productsData} />
`The ProductsList component correctly receives product data as props`

it seems that your `ProductsList`  must receive  productsData like props.
and `ProductCard` must receive product.

you can name `productsData` just like `products`

better to name props like original name of props  - `products={products}`

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/productList/ProductList.component.tsx
> +    <main className={styles.main}>
why do you use `<main>` tag here?

2024-05-10 14:08 UTC, vadym-zinchenko-moc commented on src/components/productList/productList.module.css
> +.main {
why do you use `main` class here?

2024-05-11 10:54 UTC, NosatskyiK commented
- Removed the unnecessary toggleCart function and replaced it with an arrow function in onClick.
- Removed unnecessary React imports
- Changed the name for useState in the cart
- Changed the productList logic
- Changed the main tag to a section and gave it the productList class

2024-05-12 15:40 UTC, vadym-zinchenko-moc approved these changes

2024-05-12 15:40 UTC, vadym-zinchenko-moc commented on src/components/productCard/ProductCard.component.tsx
> +    <>
extra Fragment

2024-05-12 16:00 UTC, vadym-zinchenko-moc approved these changes

2024-05-12 16:01 UTC, merged