added topics and the ability to change them, also added a filter bar
NosatskyiK/fe-react-2024 pull request #5
Opened 2024-05-22 09:41 UTC by NosatskyiK

Acceptance Criteria for 1

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  Added layout of Search Bar
- [ ]  Rewritten all styles with Module Styles
- [ ]  Implemented dynamic theme change logic

Acceptance Criteria for 1*

- [ ] Implemented logic for fetching user's theme.
- [ ]  Saved theme to the Local storage.

2024-05-22 10:00 UTC, vadym-zinchenko-moc requested changes

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/header/header.module.css
> +  background-color: #656565;
better create and use var in the whole project

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/sortList/SortList.components.tsx
> +                    <div className={styles.listBody}>
better use <ul + <li and more better use select and customize 
https://www.w3schools.com/howto/howto_custom_select.asp

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/sortList/SortList.components.tsx
> +    const toggleList = () => setShowList(!willShowList);
you can use setShowList(!willShowList) instead of creating new method

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/cart/Cart.component.tsx
> +                <svg xmlns="http://www.w3.org/2000/svg" className={styles.cartSvg}>
seems like another component with props. It's hard to read here in component

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/header/Header.component.tsx
> +                className={`${styles.themeDayBtn} ${activeTheme === 'light' ? styles.activeTheme : ''}`}
you can use clsx for this

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/header/Header.component.tsx
> +                <svg className={styles.svgThemeButton} viewBox="0 0 20 20">
same maybe another component

2024-05-22 10:00 UTC, vadym-zinchenko-moc commented on src/components/header/Header.component.tsx
> +                        className={`${styles.pathSvgTheme} ${activeTheme === 'dark' ? styles.activeButtonTheme : styles.inactiveButtonTheme}`}
clsx?

2024-05-25 13:13 UTC, NosatskyiK commented
1. Додав кольор через var для класу .vertLine.
2. Замінив div на ul та li в кастомному списку.
3. Видалив непотрібну функцію.
4. Пробував додати vite-svg-react-loader щоб додавати svg файли як компоненти, але в результаті так і не вийшло, тому поки що виніс svg в окремий компонент щоб код краще читався в header та cart.
5. Додав clsx

2024-05-26 11:32 UTC, vadym-zinchenko-moc requested changes

2024-05-26 11:32 UTC, vadym-zinchenko-moc commented on src/components/filtersBar/filtersBar.module.css
> +  background-color: #D43824;
in the future use pls variable for all colors in project

2024-05-30 07:44 UTC, vadym-zinchenko-moc approved these changes

2024-05-30 07:44 UTC, merged